version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=BackendForms;User=sa;Password=Your_password123;TrustServerCertificate=True;
    networks:
      - backendforms-network

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_password123
    ports:
      - "1433:1433"
    container_name: sql_server
    networks:
      - backendforms-network



  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - api
    networks:
      - backendforms-network

networks:
  backendforms-network:
    driver: bridge
